name: Deploy-Pipeline

on:
  #push:
  #  branches:
  #      - 'main'

  workflow_dispatch:

jobs:
    push_to_registry:
        name: Push Docker-Image to DockerHub
        runs-on: ubuntu-latest
        steps:
        - name: Check out the repo
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
    
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.MDMJAVAPROJECT_REGISTRY_PASSWORD }}
    
        - name: Build and push Docker image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            tags: komendan/mdm-java-project:latest


    deploy:
        runs-on: ubuntu-latest
        needs: push_to_registry
        environment:
            name: 'production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'mdm-java-project'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_ce8e3903aeae4cd29b70a7bbc5cd4700 }}
            images: 'index.docker.io/komendan/mdm-java-project:latest'